import { Button } from '@mui/material'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Feed from '../components/Feed'
import { useContext } from 'react'
import { AuthContext } from '../context/auth'
import { useRouter } from 'next/router'

export default function Home() {
  const { user } = useContext(AuthContext);
  const Redirect = () => {
    const router = useRouter();
    router.push('/login');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Fun Fly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user?.uid?
        <Feed /> : <Redirect />
      }
    </div>
  )
}
