import { Button } from '@mui/material'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fun Fly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
    </div>
  )
}
